## Creating emotion and behavior test sets 

    from random selection of unused data

In [1]:

import pandas as pd
import numpy as np
import os
import glob
import matplotlib.pyplot as plt
from matplotlib.image import imread 
import PIL
from PIL import Image
from numpy import asarray
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.applications.resnet import preprocess_input
from keras.applications.resnet import ResNet50
from keras.models import Model
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import confusion_matrix
from keras.preprocessing.image import ImageDataGenerator
import seaborn as sns
import matplotlib.pyplot as plt

import pickle
import h5py
from pickle import dump

### Loading emotion data

In [2]:
testing_emo_ = pd.read_csv('data/MotionEmotion/test_emo_dataset.csv')
testing_emo_

,Unnamed: 0,test_path,test_labels
0,0,data/MotionEmotion/Motion_Emotion_Dataset/vide...,6
1,1,data/MotionEmotion/Motion_Emotion_Dataset/vide...,6
2,2,data/MotionEmotion/Motion_Emotion_Dataset/vide...,6
3,3,data/MotionEmotion/Motion_Emotion_Dataset/vide...,6
4,4,data/MotionEmotion/Motion_Emotion_Dataset/vide...,6
...,...,...,...
39214,39214,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
39215,39215,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
39216,39216,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
39217,39217,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
39218,39218,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1

In [3]:
nothing = testing_emo_[testing_emo_['test_labels']== 0].index
nothing
testing_emo_.drop(nothing , inplace=True)
testing_emo_

,Unnamed: 0,test_path,test_labels
0,0,data/MotionEmotion/Motion_Emotion_Dataset/vide...,6
1,1,data/MotionEmotion/Motion_Emotion_Dataset/vide...,6
2,2,data/MotionEmotion/Motion_Emotion_Dataset/vide...,6
3,3,data/MotionEmotion/Motion_Emotion_Dataset/vide...,6
4,4,data/MotionEmotion/Motion_Emotion_Dataset/vide...,6
...,...,...,...
39214,39214,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
39215,39215,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
39216,39216,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
39217,39217,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
39218,39218,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1

In [4]:
test_seq_1 = testing_emo_[testing_emo_['test_labels']==1].sample(n=200)
test_seq_2 = testing_emo_[testing_emo_['test_labels']==2].sample(n=200)
test_seq_3 = testing_emo_[testing_emo_['test_labels']==3].sample(n=200)
test_seq_4 = testing_emo_[testing_emo_['test_labels']==4].sample(n=200)
test_seq_5 = testing_emo_[testing_emo_['test_labels']==5].sample(n=200)
test_seq_6 = testing_emo_[testing_emo_['test_labels']==6].sample(n=200)
test_set = pd.concat((test_seq_1,test_seq_2,test_seq_3,test_seq_4,test_seq_5,test_seq_6))
test_set

,Unnamed: 0,test_path,test_labels
35484,35484,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
15885,15885,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
17497,17497,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
13773,13773,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
11741,11741,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
...,...,...,...
13638,13638,data/MotionEmotion/Motion_Emotion_Dataset/vide...,6
13543,13543,data/MotionEmotion/Motion_Emotion_Dataset/vide...,6
26468,26468,data/MotionEmotion/Motion_Emotion_Dataset/vide...,6
15519,15519,data/MotionEmotion/Motion_Emotion_Dataset/vide...,6
33942,33942,data/MotionEmotion/Motion_Emotion_Dataset/vide...,6

### Exporting reduced emotion test set

In [5]:
test_set.to_csv('data/MotionEmotion/test_set.csv', encoding='utf-8')

### Loading behaviour data

In [6]:
besting_beh = pd.read_csv('data/MotionEmotion/test_beh_dataset.csv')
besting_beh

,Unnamed: 0,test_path,test_labels
0,0,data/MotionEmotion/Motion_Emotion_Dataset/vide...,5
1,1,data/MotionEmotion/Motion_Emotion_Dataset/vide...,5
2,2,data/MotionEmotion/Motion_Emotion_Dataset/vide...,5
3,3,data/MotionEmotion/Motion_Emotion_Dataset/vide...,5
4,4,data/MotionEmotion/Motion_Emotion_Dataset/vide...,5
...,...,...,...
39919,39919,data/MotionEmotion/Motion_Emotion_Dataset/vide...,2
39920,39920,data/MotionEmotion/Motion_Emotion_Dataset/vide...,2
39921,39921,data/MotionEmotion/Motion_Emotion_Dataset/vide...,2
39922,39922,data/MotionEmotion/Motion_Emotion_Dataset/vide...,2
39923,39923,data/MotionEmotion/Motion_Emotion_Dataset/vide...,2

In [7]:
nothing = besting_beh[besting_beh['test_labels']== 0].index
nothing
besting_beh.drop(nothing , inplace=True)
besting_beh

,Unnamed: 0,test_path,test_labels
0,0,data/MotionEmotion/Motion_Emotion_Dataset/vide...,5
1,1,data/MotionEmotion/Motion_Emotion_Dataset/vide...,5
2,2,data/MotionEmotion/Motion_Emotion_Dataset/vide...,5
3,3,data/MotionEmotion/Motion_Emotion_Dataset/vide...,5
4,4,data/MotionEmotion/Motion_Emotion_Dataset/vide...,5
...,...,...,...
39919,39919,data/MotionEmotion/Motion_Emotion_Dataset/vide...,2
39920,39920,data/MotionEmotion/Motion_Emotion_Dataset/vide...,2
39921,39921,data/MotionEmotion/Motion_Emotion_Dataset/vide...,2
39922,39922,data/MotionEmotion/Motion_Emotion_Dataset/vide...,2
39923,39923,data/MotionEmotion/Motion_Emotion_Dataset/vide...,2

In [8]:
test_seq_1_ = besting_beh[besting_beh['test_labels']==1].sample(n=200)
test_seq_2_ = besting_beh[besting_beh['test_labels']==2].sample(n=200)
test_seq_3_ = besting_beh[besting_beh['test_labels']==3].sample(n=200)
test_seq_4_ = besting_beh[besting_beh['test_labels']==4].sample(n=200)
test_seq_5_ = besting_beh[besting_beh['test_labels']==5].sample(n=200)
test_set_ = pd.concat((test_seq_1_,test_seq_2_,test_seq_3_,test_seq_4_,test_seq_5_))
test_set_

,Unnamed: 0,test_path,test_labels
11236,11236,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
3885,3885,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
11329,11329,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
1919,1919,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
11187,11187,data/MotionEmotion/Motion_Emotion_Dataset/vide...,1
...,...,...,...
13141,13141,data/MotionEmotion/Motion_Emotion_Dataset/vide...,5
31830,31830,data/MotionEmotion/Motion_Emotion_Dataset/vide...,5
10188,10188,data/MotionEmotion/Motion_Emotion_Dataset/vide...,5
16226,16226,data/MotionEmotion/Motion_Emotion_Dataset/vide...,5
30336,30336,data/MotionEmotion/Motion_Emotion_Dataset/vide...,5

### Exporting behaviour reduced test dataaset

In [11]:
test_set_.to_csv('data/MotionEmotion/test_set_beh.csv', encoding='utf-8')